export const SET_LATEST_NEWS = "SET_LATEST_NEWS";
export const SET_POPULAR_NEWS = "SET_POPULAR_NEWS";
export const SET_LATEST_NEWS_ERROR = "SET_LATEST_NEWS_ERROR";
export const SET_POPULAR_NEWS_ERROR = "SET_POPULAR_NEWS_ERROR";
export const SET_LOADING_DATA = "SET_LOADING_DATA";
export const SET_SIGNUP_STATUS = "SET_SIGNUP_STATUS";
export const SET_REGISTERED_USER = "SET_REGISTERED_USER";
